version: 1
current_profile: 649ac17a-f602-445a-ba56-6b7007b11343:70121:4ed3f856-3303-44d2-acae-d1b9235ee2f1
profiles:
    - site: meratsu.atlassian.net
      cloud_id: 649ac17a-f602-445a-ba56-6b7007b11343
      account_id: 70121:4ed3f856-3303-44d2-acae-d1b9235ee2f1
      display_name: Bjørn Pollen
      email: bjoernpollen@gmail.com
      auth_type: oauth
      token: !!binary |
        uC2IHk7qNhgr4jSM2gJOzeOAFg7MHpmCZvKeEZukcCU6Ojo4ODllNTBkZTQ5NmIyZWYxY2
        JkZTI2NTEyZmFmOTY5NWQ3MWE1NmVjYTJkMjRjMjNkYmI1ZDhlNjdmMzM2ZGM1ODhjMWEx
        OTRkZGQzOTUzNWY3OTVkYmFjMzU0MmY4NGVjN2Q0YzA3ZWZjNDUxMWM4N2Q1M2ExZTRjZW
        ZlZjNkY2RjNjRjNmMzMGY4YWQ3ZWU0OTNjOGEyYWNlNTRjOGMzMDM3NmM5MGRiYzM2NWIz
        OWE0OWZiY2JmMGU5OTM0ZWE5NDM0MGYwYjYwOGQ4ZGExZjQ4NTZmYTRiYzZiMWUzZGIwYj
        VhNGFjMzE0MGZkZGIyMGNiMDE1NzkzN2QzZTZkNmI4MmRhMTcxODU1NDRmMDIxNDI0OGM2
        Nzk1N2VhNTc3Y2M2YzllN2I1NmQ4YzI2NTdjMWQ3MTIxOWJlYzkzNzRmODQ4NjkxZWUxOD
        BkMzMzMzk0NmY1NzExZTc3YWE4YzVjYTg1MDQ0YjlhM2U5ZjgwNWU3YmM4ZDEzZDVjMDcy
        ZmZmZWM2N2RhYjYzMTcwMGU0ZTFjODRiOTdlZTc1NDE1MGI4MGFlMGE0YjkzODQ4OTE1Zj
        NjYmU1ZGJjYmMzMGFmMzQ4ZGFhOGJhMGNkNzE5Y2EyMjJkMjczNWQ2YzE1ZjlkNDRiZWNj
        YzBiNGFiZDMxN2JjNGMzMjI4ODg1M2ZkZmQ0MmNlMTFiZTM1YTRkNjI3NzZhN2Q1MzM3Ym
        UyM2Y3NGQ1M2VlNWE2YTM0ZmJmZGRlMDRhZWM0YWE2MWE1OWI1M2E2NjVlOWI0ZDAxNzlm
        MGY1NmZiYWRiNDE2ZTk5MmNmZGFlNTczNjUyYzQzMzNjODBkMTJmYWQwYWM1YTc2NTA2YW
        Q4NTBiNzliNTIzMjA4MzI4OTkwZWFmMWE4MDg4YTU0NTA2MjViNjU1ODgyMDRkMzQ3YmEx
        ODhlMWVjZWJiYjc4MTE3Y2UwOWYzZDVkZmIyMzAwNzc3YTZmODY3N2EyYTAwZjZmM2RjZj
        M5Y2JjMzNjYmRlNjg5NTJjY2MxOWUwODMzMGEwNDY2M2RlYmFlNDdjY2U2MmU3NjY2YTlk
        NzE1ZjMyNWI3OTFjZjBiMzFhY2MzMjcyZDRhYTFlNzE3ZjY5NjlmNjc4OTg3ZDc2ZTkyZT
        MxOTg0NTI5ODNiY2RmY2M1NjIzNDU1Y2M5NWNjODA1NTExNjBkMDBlNzE5MTNkYWQ4MmQw
        ZjhmM2UyMDBmZGFmZDNjNzc2MmI1MzRkZmI1MTZjY2I2MGNiM2JmODA5NTExMjM0MjE4Yj
        c2ZjA4ZGFiZWU0ZmEzMjg4Yzc5OGY3NTIxMTJlYTkxMDc1MGQwOWE5NTFmMzk5ZGI4NjU1
        MThmNTY2NGM1ZGE2NTFiNTRjOWU1OGU4YjMxNDg1NDgwNDlkYjdlOTViMTRmYzZlMzYwOG
        QxZTk5YjkzMTZlMmNmNmVhYzE3NjZkZDRkMWUyNWFiNDcxNmE5NDE5M2VjOTI2NTQyOWEz
        NjZiZGViZDViZTY4MjBhZjNlZTBkOTRmZWJlYzQ2N2MzNWIwYzkyZmM3ZmVlMmIzZGQyYW
        UyYTJiMzI2ZDU5ZjE1NDQ5Mzk0YmM5NjIzODhiNzQ2YzE1NTJlZDkzZTk1NGI2NWQxOTk1
        NmZlZjBjNTA4Zjk2OGZmMTg2YTk1M2IxZjA5ZDQ4ZjNkYjM4ZjU5NDQ1MjU4NDg3YmE2Ym
        IzMzgwNjQzNzZlYmU3NjQ1Mjk3ODBjYTllYzI0MjU3ZWQ5MmI1NGViYmM5YjA4MTliMTAz
        NjY5Yjc0MmI0OWU1NmY4N2Y1M2RkZGJlZjJkYjc3ZTZiNDRkNjllZjAzNjg0NDZlZjQzOT
        I0YjNiMmZhZTRlNWVlN2Y2MTg0M2JkYjA0YjI4MDE2MmM0ZDlmNjhkNmY3OTFjYWM1ZTk5
        ZWVhMjA0MzMwZjdjM2JiZDA1ZGE2ZTg5MWRkMjAzMDU1MzRlNjUwYzFiZjZkNzU3MzExNm
        JhMGY1NDhjN2Q5OGEzMjJmNDgxYzY0ZDFkMjE1ZThjYWRjYTdjYWJkMjA5YWQ3NTUwOGJl
        NDdkYzRmMWMzN2FiMmRmNTY0MzU4NTcwZTE1NGE1M2ZhODJlMmNhNmY5YjAzOTJlOTQ0YT
        g0MTE1YjRjMDgxMjk2MWQ4NDRiZWY2YjE0YWQyYTU3ZGU4Njk2ODk2NWZiYzc2NWU4NWZj
        NTAwMDczN2UwNmMxMThiZTNiZTJmYjRiNjI3Njg5M2RiOTBmZDdjZmE0NWM2NjQ2OGEyYz
        Q1MzcwOTJhMGEyMWZiYzFmZWQ5MWFjOWQzZmEzY2I1NzQ4YWFmYjM0ZjIwZDc5YWVhODUy
        MjYzZjBmMTRhZjljNzhlZmFjMTQzNmE4MzJhOGNhODk5Y2RhZWFmZTI5ZDA2NTNiM2ZjM2
        JmZjRkZDhkZDhjYzQ2NmMwMjUwZTAxYjM1ZmI4NWJlZDYxNTVhYmU0NTRmMGQ1MDZhM2Zh
        ZGVjNzMyN2JmNWQ2MzIyODk3Njk1MDBkMmVlYjZlY2YyZjg5MDUyN2NlZmMzMTIzYjY2ZG
        I1ZDMzYzI3ODc1M2FlZGVjYmE1Y2UzZjVhZWI5NDYxYjBhZTA0MGQ3MTYzMDFhOWY2NTM4
        NjljMDlmMjQ5MmJhOTljMmIxMjg1ZWU0YWJjYjQ0NmM4NDJjODNjMzkwMzJhMmQxNDUwZj
        k0NjA5MjlkMjY4ZjYxYWM4NzhiMWU4NDFiMjUzNzRjYWZhNzJhZDY1MGI4OTQ1ZjEwNzg1
        NGJiNmZlNDkwZmZjMTFiMWI0N2ViYTM0MGMzMjUwMmQ5YTMzODhmMGUxNmE4ODhmYWVmZG
        ZiY2ZjNjBlMjUzMjY3ZGQ5ZWM4YjkwY2FlN2JjODc2MGNkOTgyNDhkMmUyNTE3OTNiNGY0
        YzNhYzhhNjM0OTUzZThlNTg0MjNlYmRiYjJlNWJhOTBhOTlhMjBhNDU5NWQ3YzI3ODQ4Nj
        Q4YTgxZGFhMDM5MTVmNTU1ZmQ4NDg3OTY4MTBiYmI5MGY2MzVhNGEzZmQ3ZTI2MjIyMzFk
        OTBjNjkyZWZjN2MxZWE3ZTI3OTRlOGMzOWQyZTc2OTRjMGNlNzM0N2Y4MDJmNmQ2MmE4Zm
        I1ZTA3ZGU5OTFjMmMxZDYyMGIyN2U2MmQzNzNkMjBiNDk2NjYyZDQ3YThjMDU3MTkyMTBh
        MzMwNTk0MzgzMjM4ZjlhNzZlYjEwZjRjYmUzOGU2MzFhNmFhMjVkZDZiMGRkOTQ0N2UzZT
        c2YzA3NWU2YjlkNzllMTk1NDYwNGEzM2Q1MDk0Y2QxMzFmNDMzOWNkZWMwMjY1M2UzNDFi
        OGZkOGQ0NzZhM2E0MWVhYzk0Y2YyZGJhY2RmNzYxZWUyM2U4YWUyOGZiODRkN2UxZjZkOG
        M1YTQ4N2VjODQ4Yjc3ZjNmOTE4MDNkNzViZmZhNDVmNWJmZGQ2MGE0ZWY3MjBhODEyZGYy
        OGNkYzIyYzBkNDcyZTcxYzJkZWU5ZWFkMzNkMTVkOTQ0NzIzMzgwZGUwZjI4ZGQ2YWM5MG
        FlN2U5YTVjMTNlNWMzYTM0YmYwZGMzMTc1MjkwYTg4YzBlNWU3MWNiNjg0ZjZiM2M4ZjUy
        YjVkNWUxNjMxYTNkOTI5MTZiZmFmYzIxZmM1NzBhNjU0OTdjZjM0ODU0ODkxODQwZDExNj
        ExNTY2MDc5NjUxN2I3M2U0ZGQ3Y2I5Nzg0NGViMGEyNGRmNWE1YzZmNTI3NWRiMDU3YTk0
        OTI4ODE4YzgyZTRjNjk4YmNhNThkNTY0MGY3YTc3NzgyYTYyZDBjMDlkZGM1ZTEyMWY3MT
        I4ZGFkZWFkOWMzNDdlZTIwMzFhZjllZmZjNWE5MDUxNDYxZGRhYWQyNjQxZDc3OTMzZGEw
        OTZiOTRmMGU3MGZiNDM5ODYwYjM5ZmQ5ODZlMTk1YmQyODBjZTg0NjI1M2I0Yzc3ZDU5M2
        M2NzU1MjdmYzcyZGVlNmY1NjBlMWRmNDkyYTY2ODY0MWM0M2U4ZDZiY2U1YTY1YjBlNzMx
        YjliNDg2N2VkNDFkY2I5YTBiNThkMDllZGFjZDAzOWM5OTEzNjVjNjU3YzVmYjUzOGExN2
        JjZTI0ZGI5NDVmM2QzNjM5NDMyZjRlZmU4MWRlZDZjMmIwOWY0OWQyMWFkNDRmMjQ1ZjU4
        NDNiNTg1YzdkZTFjMjgyN2E5NWRlNTQwYjM0MWJlMWFhYmExOGNjYmZlYmZhZDQ3MTBlNT
        kxZWMxN2Y4ZTY2MDlmYzQyNTA5MTFkZTIzYzYxODEyZTAxNzdlYjYzOGQ1ODg5N2UwOWJj
        ZTczMzVlM2VmYTQ0MDljNjdkMDA1MGQwODY3NTdiMmU3N2NkZWQ2ZjE4NjY0NTc2N2Q1OW
        QxMDI5YWIwYTZhNzg3MjYyNDIwM2JjZTk2YjI0NzBjZjk3MDU4ZjQxOWJkMTY4MTQyOWMw
        YTZhZDMzOTk4ZWI5YjcxMGQ1MmVhNTUwNDI4NmZmMzY5ODVmYzU2MzUxZjFmNjhmZGRkOW
        M1N2QyMTljMGJjNGQ1MDJmOTljMzdmMjVkOTUxOWQyYjc2MTNjOTNiNDRlYjA5ZTE5OGRi
        NjRhZWI3NzFlOWM5NjEwZmFhZDk2NTdhNjg0ZDc2OWU0ODUyNzkyNTQzMjQ0YTllZjkxOG
        E4YzZiMWEyZWQwNTU2ZTJjMTdmN2Q3YTAyMDJhZTVmZmE1OGE0NjZiYWRjY2IxNzhlZjE3
        NzlhY2I3MTMxZGViZTQzYmFhN2NlYTljNDFlZjhjZjZmMjgwOWEyNjU4MjhlYzkxZjgxZG
        Q1NDk5ZGZhNGIwMzg5MGU3Njg3N2M5ODMzM2MxZGJiYzEwYjY4N2Y1NjkzOGYwNWVkMWQ1
        MWFjNmRiODMzYjNmOTlmOWE3YjM1OTBhNTVhMDg0NTZlYjk0NjRhMWQ4OGVjY2U1MDU3Y2
        ExMDdiMmI3NjU2OThhN2IxZTQwZGY3MGY0Y2U1MzAxMjI2NDczNTBhYTJkYmFiMGUyODBm
        YzY0ZTI5MjdlY2NkNjg0YzI1YjQ2ODczMzBmMmM5MDZiZWU0ZWRkY2FjMWIyZjMxZDJkOT
        YzNGZiZmI1YTM4ZmM5ODcxYTYxOTZkNmUwZDAwMzMzZWFhMWQxYzI0YTIwZmUzM2NhN2Ex
        MDQ4YTVhYzM4Zjk0YzIwNjU3NmRjMmVhMWNiNWJiNTJiMjViMWNlMjNjZGJiNTc2OTkwMW
        RkODUwMjE4MDdjZmY0OTYwMmEyNGExYTA3YWFjNDkzMGY1YjI5OGYzMGI1ZTM4ZDE3Y2M4
        MzhkNzRjNGIzYjY2OTFiMWI1ZTBiMjdjZGVjZWVmZDFmNDYzZmI1NjI0ODNhZjMzNzk2ZD
        hhMzU5OWM4NWRkNzZmNjkwNzQyMDVkMjAzZDRjNzI0MzNiNTJiZDg2M2RlNjY5ZjU5YmZi
        ZGFlMDc0OTk1YzdiYzM5NWY2MDk2NGQwOWUyMTk3NWE5YjdiM2EzYjNkMjIwZGVhNjYxZT
        U4NzE4NWJmNDQ3NGJjM2UwNTBmMDJmMDUxNDU1MTg1MmE4OGJiNTc0YzRmZjdkNGNiZDFh
        ZTFhNTg2MDVkNWE2MTRhMmU0YjhmZjcyNTBhMzRmNmE0YzkxMDI1NzRmYmEwMjNkYzAxZD
        UwOGM2NjVhOTliYWQzNzRjNzNjN2JjNjZkYmM2ZTA2MjI3Nzk5ZA==
