[General]
beep=false
eject=true
telemetry=true
x=1287
y=20

[imagecustomization]
hostname=meratsu
keyboardLayout=us
sshEnabled=true
sshUserName=pollen
sshUserPassword=$5$.i1OFVnK0k$ju/i4FP2vTkCP3695jORmR6SOImlvPyeLPjrtExzb41
timezone=Europe/Oslo
wifiCountry=NO
wifiPassword=68b64e25a4cf16c916c4af15fc99a7f83c4e2a96865c4c2c886c30bf19492ef8
wifiSSID=KliinKokkus
